-- Habilita extensões necessárias
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABELA CATEGORIAS
CREATE TABLE IF NOT EXISTS categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    imagem_url TEXT,
    ordem INTEGER DEFAULT 0,
    ativo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABELA PRODUTOS
CREATE TABLE IF NOT EXISTS produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    marca TEXT DEFAULT 'Bora Heart Glow',
    categoria_id BIGINT REFERENCES categorias(id) ON DELETE SET NULL,
    descricao TEXT,
    detalhes JSONB DEFAULT '{}'::jsonb,
    preco_original DECIMAL(10,2) DEFAULT 0,
    preco_atual DECIMAL(10,2) DEFAULT 0,
    parcelas INTEGER DEFAULT 1,
    cores JSONB DEFAULT '[]'::jsonb,
    tamanhos TEXT[] DEFAULT '{}',
    imagem_principal TEXT,
    imagens TEXT[] DEFAULT '{}',
    midias JSONB DEFAULT '[]'::jsonb,
    estoque INTEGER DEFAULT 0,
    estoque_por_variacao JSONB DEFAULT '{}'::jsonb,
    destaque BOOLEAN DEFAULT false,
    novidade BOOLEAN DEFAULT false,
    ativo BOOLEAN DEFAULT true,
    avaliacao DECIMAL(3,2) DEFAULT 5.0,
    total_avaliacoes INTEGER DEFAULT 0,
    total_vendas INTEGER DEFAULT 0,
    meta_title TEXT,
    meta_description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABELA PEDIDOS
CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT UNIQUE NOT NULL,
    cliente_id UUID,
    cliente_nome TEXT,
    cliente_email TEXT,
    cliente_telefone TEXT,
    itens JSONB DEFAULT '[]'::jsonb,
    subtotal DECIMAL(10,2) DEFAULT 0,
    desconto DECIMAL(10,2) DEFAULT 0,
    frete DECIMAL(10,2) DEFAULT 0,
    total DECIMAL(10,2) DEFAULT 0,
    cupom_codigo TEXT,
    endereco_entrega JSONB DEFAULT '{}'::jsonb,
    metodo_envio JSONB DEFAULT '{}'::jsonb,
    codigo_rastreio TEXT,
    transportadora TEXT,
    forma_pagamento TEXT,
    status_pagamento TEXT DEFAULT 'Pendente',
    mp_payment_id TEXT,
    mp_preference_id TEXT,
    status TEXT DEFAULT 'Pendente',
    historico_status JSONB DEFAULT '[]'::jsonb,
    observacoes_internas TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABELA SECOES HOME
CREATE TABLE IF NOT EXISTS secoes_home (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave TEXT UNIQUE NOT NULL,
    nome TEXT NOT NULL,
    visivel BOOLEAN DEFAULT true,
    ordem INTEGER DEFAULT 0,
    config JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABELA BANNERS HERO
CREATE TABLE IF NOT EXISTS banners_hero (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imagem_desktop TEXT NOT NULL,
    imagem_mobile TEXT,
    titulo TEXT,
    subtitulo TEXT,
    texto_botao TEXT,
    link_botao TEXT,
    cor_botao TEXT DEFAULT '#8B3A6B',
    posicao_texto TEXT DEFAULT 'esquerda',
    ativo BOOLEAN DEFAULT true,
    ordem INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABELA APARENCIA
CREATE TABLE IF NOT EXISTS aparencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cores_primarias JSONB DEFAULT '{"brand": "#04548c", "background": "#ffffff", "text": "#111111", "highlight": "#22c55e"}'::jsonb,
    fontes JSONB DEFAULT '{"heading": "Outfit", "body": "Outfit"}'::jsonb,
    layout JSONB DEFAULT '{"card_radius": 20, "button_radius": 12}'::jsonb,
    logo_url TEXT,
    favicon_url TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. TABELA CONFIGURACOES
CREATE TABLE IF NOT EXISTS configuracoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave TEXT UNIQUE NOT NULL,
    valor JSONB,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. TABELA CLIENTES (Opcional se usar Supabase Auth)
CREATE TABLE IF NOT EXISTS clientes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    nome TEXT,
    email TEXT UNIQUE NOT NULL,
    telefone TEXT,
    cpf TEXT,
    data_nascimento DATE,
    genero TEXT,
    enderecos JSONB DEFAULT '[]'::jsonb,
    segmento TEXT DEFAULT 'Varejo',
    notas_internas TEXT,
    total_pedidos INTEGER DEFAULT 0,
    total_gasto DECIMAL(10,2) DEFAULT 0,
    ultimo_pedido TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- BUCKET DE STORAGE (Manual via Dashboard Supabase, mas aqui registro o nome)
-- Criar bucket público chamado: product-media

-- POLÍTICAS DE ACESSO (RLS - Desabilitado para facilitar o fluxo inicial, mas em produção deve ser configurado)
ALTER TABLE produtos DISABLE ROW LEVEL SECURITY;
ALTER TABLE categorias DISABLE ROW LEVEL SECURITY;
ALTER TABLE pedidos DISABLE ROW LEVEL SECURITY;
ALTER TABLE secoes_home DISABLE ROW LEVEL SECURITY;
ALTER TABLE banners_hero DISABLE ROW LEVEL SECURITY;
ALTER TABLE aparencia DISABLE ROW LEVEL SECURITY;
ALTER TABLE configuracoes DISABLE ROW LEVEL SECURITY;
ALTER TABLE clientes DISABLE ROW LEVEL SECURITY;
